// FETCHING
export const FETCH_TRAILS = 'FETCH_TRAILS'
export const FETCH_REGIONS = 'FETCH_REGIONS'

// SEARCHING
export const CHANGE_SEARCH_TERM = 'CHANGE_SEARCH_TERM'

// MAP
export const LOCATION_FOUND = 'LOCATION_FOUND'
export const FIT_MAP_BOUNDS = 'FIT_MAP_BOUNDS';
export const MAP_ZOOM_CHANGED = 'MAP_ZOOM_CHANGED';
export const MAP_CENTER_CHANGED = 'MAP_CENTER_CHANGED';

export const FEATURE_CLICKED = 'FEATURE_CLICKED';

export const CHANGE_TRAIL_STYLE = 'CHANGE_TRAIL_STYLE';
export const CHANGE_REGIONS_VISIBILITY = 'CHANGE_REGIONS_VISIBILITY';
